apiVersion: v2
name: doku
description: A Helm chart for Doku
type: application
version: 0.1.3
appVersion: 0.1.3
icon: https://raw.githubusercontent.com/dokulabs/.github/main/profile/assets/logo-orange-bg.jpg

maintainers:
  - name: patcher99
    email: patcher99@dokulabs.com
