# Overrides the default name for the release.
nameOverride: ""
# Overrides the default fullname for the release.
fullnameOverride: ""

# Doku Client configuration
client:
  # Toggle to enable/disable the Doku Client
  enabled: true
  # Number of replicas for the Client
  replicaCount: 1

  # Image repository and tag
  image:
    repository: ghcr.io/dokulabs/doku-client
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  # List of secrets containing credentials to pull images
  imagePullSecrets: []

  # Kubernetes Service configuration for the client
  service:
    # Type of service (e.g., LoadBalancer, NodePort)
    type: LoadBalancer
    # Port on which the service is exposed
    port: 3000
    # Session affinity configuration
    sessionAffinity: None

  # Resource limit and request configuration for the client pod
  resources:
    limits:
      cpu: 1000m
      memory: 1280Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Annotations to be added to the client pods
  podAnnotations: {}

  # Node labels for pod assignment
  nodeSelector: {}

  # Tolerations for pod assignment
  tolerations: []

  # Affinity for pod assignment
  affinity: {}

  # Client-specific configurations
  config:
    # secret:
    #   # Name of the secret that contains the ClickHouse User and Password
    #   name: ""
    #   # Key in the secret that contains the ClickHouse User's password
    #   passwordKey: ""
    #   # Key in the secret that contains the ClickHouse User name
    #   usernameKey: ""

    # SQLite database URL (where the data is stored)
    sqlite_url: file:/app/client/data/data.db

    # Configuration for the Doku Backend Database (ClickHouse)
    database:
      name: default
      # if you set secrets.existingSecret to true, Skip the username field
      username: default
      # if you set secrets.existingSecret to true, Skip the password field
      password: DOKU
      host: "doku-db.default.svc.cluster.local"
      port: "8123"

# Doku Ingester configuration
ingester:
  # Toggle to enable/disable the Doku ingester
  enabled: true
  # Number of replicas for the ingester
  replicaCount: 1

  # Image repository and tag
  image:
    repository: ghcr.io/dokulabs/doku-ingester
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  # List of secrets containing credentials to pull images
  imagePullSecrets: []

  # Ingester Service Configuration
  service:
    # Type of service (e.g., LoadBalancer, NodePort)
    type: LoadBalancer
    # Port on which the service is exposed
    port: 9044
    # Session affinity configuration
    sessionAffinity: None

  # Resource limit and request configuration for the ingester pod
  resources:
    limits:
      cpu: 1000m
      memory: 1280Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # Annotations to be added to the ingester pods
  podAnnotations: {}

  # Node labels for pod assignment
  nodeSelector: {}

  # Tolerations for pod assignment
  tolerations: []

  # Affinity for pod assignment
  affinity: {}

  config:
    # secret:
    #   # Name of the secret that contains the ClickHouse User and Password
    #   name: ""
    #   # Key in the secret that contains the ClickHouse User's password
    #   passwordKey: ""
    #   # Key in the secret that contains the ClickHouse User name
    #   usernameKey: ""

    # URL to download Pricing data file. Recommneded is to use the default URL provided by Doku
    pricing:
      url: "https://raw.githubusercontent.com/dokulabs/doku/main/assets/pricing.json"

    # Configuration for the Doku Backend Database (ClickHouse)
    database:
      name: default
      # if you set secrets.existingSecret to true, Skip the username field
      username: default
      # if you set secrets.existingSecret to true, Skip the password field
      password: DOKU
      host: "doku-db.default.svc.cluster.local"
      port: "9000"
      maxOpenConns: "10"
      maxIdleConns: "10"

# ClickHouse database configuration (used as the backend for Doku)
clickhouse:
  # Toggle to enable/disable the ClickHouse database deployment
  enabled: true

  # Docker image configuration for ClickHouse
  image:
    repository: clickhouse/clickhouse-server
    tag: 24.2.2
    pullPolicy: IfNotPresent

  # Authentication configuration for ClickHouse
  auth:
    secret:
      # Name of the secret that contains the ClickHouse User and Password
      name: ""
      # Key in the secret that contains the ClickHouse User's password
      passwordKey: ""
      # Key in the secret that contains the ClickHouse User name
      usernameKey: ""

    # if you set clickhouse.secret, Skip this username field
    user: default
    # if you set clickhouse.secret, Skip this password field
    password: DOKU

  # Kubernetes Service configuration for ClickHouse
  service:
    type: LoadBalancer

  # Persistent storage configuration for ClickHouse
  persistence:
    # storageClassName: ""
    # Access mode for the persistent volume
    accessMode: ReadWriteOnce
    # Size of the persistent volume
    size: 10Gi

  # resources:
  #   limits:
  #     cpu: 1000m
  #     memory: 1280Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

# Ingress configuration (for exposing Doku via an ingress)
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
