{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "doku.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "doku.fullname" . }}-client
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "doku.fullname" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "doku.fullname" . }}-client
    spec:
      containers:
      - name: doku-client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.client.service.port }}
        env:
        {{- if .Values.clickhouse.enabled }}
        - name: INIT_DB_HOST
          value: "{{ .Release.Name }}-db.{{ .Release.Namespace }}.svc.cluster.local"
        {{- else }}
        - name: INIT_DB_HOST
          value: "{{ .Values.client.config.database.host  }}"
        {{- end }}
        - name: INIT_DB_PORT
          value: "{{ .Values.client.config.database.port }}"
        - name: INIT_DB_DATABASE
          value: "{{ .Values.client.config.database.name }}"
        - name: SQLITE_DATABASE_URL
          value: "{{ .Values.client.config.sqlite_url }}"
        {{ if .Values.client.config.secret }}
        - name: INIT_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.client.config.secret.name }}
              key: {{ .Values.client.config.secret.usernameKey }}
        - name: INIT_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.client.config.secret.name }}
              key: {{ .Values.client.config.secret.passwordKey }}
        {{ else }}
        - name: INIT_DB_USERNAME
          value: "{{ .Values.client.config.database.username }}"
        - name: INIT_DB_PASSWORD
          value: "{{ .Values.client.config.database.password }}"
        {{- end }}
        resources:
          {{- toYaml .Values.client.resources | nindent 10 }}
      imagePullSecrets:
      {{- range .Values.client.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.client.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.client.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.client.affinity | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "doku.fullname" . }}-client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.port }}
  selector:
    app: doku-client
  sessionAffinity: {{ .Values.client.service.sessionAffinity }}
{{- end }}